[package]
name = "javaver"
version = "0.1.0"
edition = "2021"
authors = ["Krazy Dev"]

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }

serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"